global:
# How frequently to scrape targets by default.
  scrape_interval: 1s

# How long until a scrape request times out.
  scrape_timeout: 1s

# A list of scrape configurations.
scrape_configs:
  - job_name: 'ratatouille'
    scrape_interval: 1s
    static_configs:
    - targets: ['10.0.13.27:9001']
