global:
# How frequently to scrape targets by default.
  scrape_interval: 1s

# How long until a scrape request times out.
  scrape_timeout: 1s

# A list of scrape configurations.
scrape_configs:
  - job_name: 'ratatouille'
    scrape_interval: 1s
    static_configs:
    - targets: ['host.docker.internal:9001']

  - job_name: 'kafka'
    scrape_interval: 1s
    static_configs:
    - targets: ['kafka:9094']
