version: '3.7'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
    - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_JAVA_OPTS: -Xmx128m -Xms128m
    networks:
    - ratatouille

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    hostname: kafka
    container_name: kafka
    depends_on:
    - zookeeper
    ports:
    - 29092:29092
    - 9092:9092
    #- 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_JAVA_OPTS: -Xmx128m -Xms128m
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
#      KAFKA_JMX_OPTS: >
#        -Djava.rmi.server.hostname=kafka
#        -Dcom.sun.management.jmxremote.rmi.port=9093
#        -Dcom.sun.management.jmxremote=true
#        -Dcom.sun.management.jmxremote.ssl=false
#        -Dcom.sun.management.jmxremote.authenticate=false
#        -javaagent:/var/lib/share/java/prometheus.jar=9094:/etc/kafka/kafka-jmx.yml
#      JMX_PORT: 9093
#    volumes:
#    - ./docker/volumes/config/kafka-jmx.yml/:/etc/kafka/kafka-jmx.yml
#    - ./docker/volumes/jmx_prometheus_javaagent-0.3.1.jar/:/var/lib/share/java/prometheus.jar
    networks:
    - ratatouille

  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
    - zookeeper
    - kafka
    ports:
    - "8081:8081"
    environment:
      SCHEMA_REGISTRY_JAVA_OPTS: -Xmx128m -Xms128m
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,OPTIONS'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
    networks:
    - ratatouille

#  landoop-schema-registry-ui:
#    image: landoop/schema-registry-ui:latest
#    depends_on:
#    - schema-registry
#    ports:
#    - "8888:8000"
#    hostname: schema-registry-ui
#    container_name: schema-registry-ui
#    environment:
#      SCHEMAREGISTRY_URL: 'http://schema-registry:8081'
#      PROXY: "true"
#    networks:
#    - ratatouille

  kafka-connect:
    image: ratatouille/cp-kafka-connect:5.3.0
    hostname: kafka-connect
    container_name: kafka-connect
    ports:
    - 8083:8083
    build:
      context: .
      dockerfile: DockerfileConnect
    environment:
      CONNECT_GROUP_ID: ratatouille-connect-group
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_JAVA_OPTS: -Xmx128m -Xms128m
      CONNECT_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,DELETE,OPTIONS
      #CONNECT_PLUGIN_PATH: '/usr/share/java,/etc/kafka-connect/jars'
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.3.0.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      command: "bash -c 'if [ ! -d /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen ]; then echo \"WARNING: Did not find directory for kafka-connect-datagen (did you remember to run: docker-compose up -d --build ?)\"; fi ; /etc/confluent/docker/run'"
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    networks:
    - ratatouille

#  prometheus:
#    image: prom/prometheus:v2.8.1
#    hostname: prometheus
#    container_name: prometheus
#    ports:
#    - "9090:9090"
#    command: --config.file=/etc/prometheus/prometheus.yml
#    volumes:
#    - ./docker/volumes/config/prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#    - ratatouille
#
#  grafana:
#    image: grafana/grafana:6.1.3
#    hostname: grafana
#    container_name: grafana
#    ports:
#    - "3000:3000"
#    volumes:
#    # - ./docker/volumes/data/graphana/:/var/lib/grafana
#    - ./docker/volumes/config/dashboards/:/etc/grafana/dashboards/
#    - ./docker/volumes/config/provisioning/:/etc/grafana/provisioning/
#    depends_on:
#    - prometheus
#    networks:
#    - ratatouille

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.3.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
      - kafka-connect
    ports:
      - 9021:9021
    environment:
      PORT: 9021
      CONTROL_CENTER_JAVA_OPTS: -Xmx128m -Xms128m
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'kafka-connect:8083'
      #CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
      #CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
    networks:
      - ratatouille

  ratatouille-datagen:
    image: ratatouille-datagen
    container_name: ratatouille-datagen
    environment:
      PORT: '7070'
      HOST: 'ratatouille-datagen'
      KAFKA_BROKERS: 'kafka:29092'
      JAVA_OPTS: -Xmx64m -Xms64m
    ports:
    - "7070:7070"
    depends_on:
    - control-center
    networks:
    - ratatouille

  ratatouille-app:
    image: ratatouille-app
    container_name: ratatouille-app
    ports:
    - "8080:8080"
    depends_on:
    - ratatouille-datagen
    networks:
    - ratatouille

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
#    hostname: elasticsearch
#    container_name: elasticsearch
#    ports:
#      - 9200:9200
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - ratatouille
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.6.1
#    hostname: kibana
#    container_name: kibana
#    ports:
#      - "5601:5601"
#    environment:
#      SERVER_NAME: kibana
#      ELASTICSEARCH_HOSTS: elasticsearch:9200
#    networks:
#      - ratatouille

networks:
  ratatouille:
